# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 666e5e63435a2b85d427ea8801f6f0b89f32f49657b17ca161d034eb47e6e826a34fd75665cea3d662cfb40ba1fda1535b2617792ebfc18f8ad5f538e4fcf3d1

test:
  secret_key_base: b4a0cb93b364d0bfcda9f31bf60a6657e7625e291e48b205aa89db20dfdd84f22e205da49281e7446d9f522783c7f65c26bfef0ab2c2e848a014ad2b70e623a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
